import type { Metadata } from "next";
import Nav from "@/components/Nav";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div style={{background:'url(\'https://voguebebucket.s3.amazonaws.com/pexels-codioful-(formerly-gradienta)-7130478.jpg\') center', backgroundSize:'cover'}} className={"w-screen h-screen"}>
      <Nav/>
      {children}
    </div>


  );
}
